feat: implement user following
liftM/pooter pull request #1
Opened 2020-01-05 00:56 UTC by emilyzhang

### what & why
- add functionality to follow users

2020-01-05 04:53 UTC, elldritch requested changes

2020-01-05 04:53 UTC, elldritch commented on api/server.go
> +	}
Disagree. Dependencies that have effects should be injected. This makes testing easier, because a consumer of `package api` can pass in their own implementation of `pooterdb.PooterDB`.

In general, effects should be provided as high-level interfaces, implemented as separate packages, and injected into effect consumers, because they make testing difficult when implemented in consuming packages themselves.

2020-01-05 04:53 UTC, elldritch commented on api/users.go
> +}
I would implement this in a separate file.

2020-01-05 04:53 UTC, elldritch commented on api/users.go
> +	FollowID string `json:"follow_id"`
What is a `FollowID`?

2020-01-05 04:53 UTC, elldritch commented on api/users.go
> +	UserID string `json:"user_id"`
Why does this return a `UserID`?

2020-01-05 04:53 UTC, elldritch commented on api/users.go
> +}
In hindsight, this probably doesn't need to return a `UserID` either.

2020-01-05 04:53 UTC, elldritch commented on api/users.go
> +	}
A lot of this code looks like boilerplate. Let's extract this into a helper function.

2020-01-05 04:53 UTC, elldritch commented on api/server.go
> +func NewServer(conn string) *Server {
How about `New` instead?

2020-01-05 04:53 UTC, elldritch commented on api/server.go
> +}
The details of the struct fields here probably shouldn't be exposed to consumers. All a consumer really cares about is the ability to start the server.

2020-01-05 04:53 UTC, elldritch commented on effects/pooterdb/pooterdb.go
> +	}
You should pass integers as arguments instead of converting string integer arguments.

2020-01-05 04:53 UTC, elldritch commented on images/pooterdb/migrations/schema.sql
> +  userid  INTEGER REFERENCES users(id)
[nit] `user_id`.

2020-01-05 04:53 UTC, elldritch commented on images/pooterdb/migrations/schema.sql
> +  followid    INTEGER REFERENCES users(id),
[nit] `user_id`, `follow_id`.

2020-01-05 04:53 UTC, elldritch commented on images/pooterdb/migrations/schema.sql
> +  followid    INTEGER REFERENCES users(id),
This naming is confusing: which one is the follower and which one is being followed?

2020-01-05 10:36 UTC, emilyzhang commented on api/users.go
> +	UserID string `json:"user_id"`
it doesn't anymore

2020-01-05 11:08 UTC, emilyzhang commented on images/pooterdb/migrations/schema.sql
> +  followid    INTEGER REFERENCES users(id),
i changed followid to "idol" - the idol of the userid in question

2020-01-05 11:11 UTC, emilyzhang commented on api/users.go
> +}
gonna keep these grouped for now unless you have strong preferences

2020-01-06 04:05 UTC, emilyzhang commented
will be merged in as part of PR #4

2020-01-06 04:05 UTC, closed without merging